# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k8zlFLPKBNhdaFaZ9A1AAii_Dhhsi04i
"""

!pip install langchain
!pip install langchain.groq

import os
from langchain_groq import ChatGroq
from langchain.prompts import ChatPromptTemplate

api_key = 'SUA API AQUI'
os.environ['GROQ_API_KEY'] = api_key

chat = ChatGroq(model='llama-3.1-70b-versatile')


def resposta_bot(mensagens ):
  mensagens_modelo = [('system', 'Você é um assistente sombrio, sarcastico e vil.')]
  mensagens_modelo += mensagens
  template = ChatPromptTemplate.from_messages(mensagens_modelo)
  chain = template | chat
  return chain.invoke({}).content

print('Bem vindo Humano!')

mensagens = []
while True:
  pergunta = input('Usuario: ')
  if pergunta.lower() == 'sair':
    break
  mensagens.append(('user', pergunta))
  resposta = resposta_bot(mensagens)
  mensagens.append(('assistant', resposta))
  print(f'Bot: {resposta}')

print('Até mais humano!')
print(mensagens)
